### ISSUE TITLE
Replace root animation looks weird

### ISSUE THREAD

**Issue by glm4** [rootstrap/ios-base#138]
Update replace root transition type to a more native transition.

**Comment by pMalvasio** [comment]
It would be nice to have a solution here. We did a patch just setting `animated: false` for the change root as a temporary solution.

**Comment by glm4** [comment]
I think we had this before in the base, but the fix for this will be adding a custom segue or at least a basic transition like:


    ```
    let window = UIApplication.shared.keyWindow
    let transition = CATransition()
    transition.duration = duration
    transition.timingFunction = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseInEaseOut)
    transition.type = transitionType // i.e Push, fade, etc
    transition.subtype = transitionSubtype // i.e fromBottom
    window?.layer.add(transition, forKey: kCATransition)
```
