### ISSUE TITLE
Improve technical documentation about R.swift and Router usage 

### ISSUE THREAD

**Issue by pMalvasio** [rootstrap/ios-base#141]
* Enhance documentation for R.swift and Router
* Explain what/how/when to use both

**Comment by glm4** [comment]
R.swift isn't going to be removed?

**Comment by pMalvasio** [comment]
I don't know. We're using it and it's not a bad thing for now 🤔 Maybe we can discuss this again later

**Comment by glm4** [comment]
I think we should mention R.swift as one of the pods included and the Navigator/Routes as part of the standard features the base provides, the same way we do in the README for existing features and pods.
For example, if someone need to know the nitty gritty of R.swift they can just go the the pod README, basic usage is covered in the example app.
