### ISSUE TITLE
Add support for .fullscreen modal on Router

### ISSUE THREAD

**Issue by pMalvasio** [rootstrap/ios-base#142]
When using `.modal` option on navigation router, add support for `.fullscreen` besides the default modal on iOS13

**Comment by glm4** [comment]
Can't this be achieved with the `TransitionConfigurator` of the `Route`?

**Comment by glm4** [comment]
According to the docs this block is exactly for that purpose.

/**
   Configuration callback executed just before pushing/presenting modally.
   Use this to set up any custom transition delegate, presentationStyle, etc.
   - Parameters:
   - sourceVc: The currently visible viewController, if any.
   - destinationVc: The (fully intialized) viewController to present.
   */


Feel free to reopen if there is anything else needed.
