### ISSUE TITLE
Retry a request in Moya with RxSwift?

### ISSUE THREAD

**Issue by prateek3255** [rootstrap/ios-base#150]
I am pretty new to RxSwift and I am using the code from the branch mvvm+rxSwift, which has the following [function for a request of given ProviderType ](https://github.com/rootstrap/ios-base/blob/121ef3b084d1bacd2a55083002e724b37e8b657e/ios-base/Networking/APIService.swift#L93)- 
```swift
    open func request<T>(for target: ProviderType,
                         at keyPath: String? = nil
                         ) -> Observable<(T, Response)> where T: Codable {
        return provider.rx.request(target)
        .filterSuccessfulStatusCodes()
        .flatMap { [weak self] response in
          let decodedValue = try response.map(T.self,
                                              atKeyPath: keyPath,
                                              using: self?.jsonDecoder ?? JSONDecoder(),
                                              failsOnEmptyData: true)
          return .just((decodedValue, response))
        }
        .asObservable()
        .catchError { [weak self] error in
          guard let self = self else {
            return Observable.error(error)
          }
          return Observable.error(self.handleError(with: error))
        }
    }
```

This works pretty well, but now I want to retry the request when the request fails with a status code of 401, after fetching the refresh token. I found [this](https://github.com/Moya/Moya/issues/1177#issuecomment-345132374) comment on a GitHub issue which tells how it can be achieved but I am still confused how it will work in my case (the comment does not provide context related to how the refresh token mechanism works).

**Comment by germanStabile** [comment]
Hi @prateek3255, thanks for the detailed issue. 

Not very into RxSwift myself, but my guess would be to capture 401 calls on `catchError`, call your refresh token endpoint, and retry the failing call if refresh is successful.

I think it could be helpful to demonstrate this kind of behavior in the ios-base, so we may update on this issue.

**Comment by glm4** [comment]
Closing due to the removal of Moya dependency
