### ISSUE TITLE
Add SnapKit as DSL for constraints

### ISSUE THREAD

**Issue by pMalvasio** [rootstrap/ios-base#184]
What about using [SnapKit](https://github.com/SnapKit/SnapKit) for writing constraints and placing views? I think this DSL improves a lot the tedious task of writing constraints by code (speed and readability).

Things like (from first PR moving from storyboards to code):
```swift
extension UIView {
...
  NSLayoutConstraint.activate([
    leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: leadingMargin),
    trailingAnchor.constraint(
      equalTo: view.trailingAnchor,
      constant: -trailingMargin
    )
  ])
...
}
```
Could be:
```swift
currentView.snp.makeConstraints {
  $0.leading.equalTo(view.snp.leading).offset(...)
  $0.trailing.equalTo(view.snp.trailing).offset(...)
}
```

Applying this change now implies no rewriting if the migration from storyboards to code continues. We'll be writing this from the begging creating the foundations for future UI.

**Comment by germanStabile** [comment]
As discussed with the team, the approach to be taken is to add our custom helpers progressively as we refactor out storyboards.
