### ISSUE TITLE
Update concurrent code to Async/Await 

### ISSUE THREAD

**Issue by glm4** [rootstrap/ios-base#191]
Swift 5.5 introduced a new concurrency framework with multiple tools and APIs.
First we should evaluate the possibility to migrate the current project to the new APIs.

**Comment by fnicola1** [comment]
would be good to start reading about Actors in swift . :D i'm in with it :)

**Comment by glm4** [comment]
[Swifter](https://github.com/httpswift/swifter) seems to be updating to Async in their version 2.0. This is a good opportunity also to check which dependencies are updating to this approach.

**Comment by danialepaco** [comment]
All services are now migrated to concurrency
