### ISSUE TITLE
Replace errors for error, and now it's a string

### ISSUE THREAD

**Issue by MaicolBen** [rootstrap/ios-base#69]
It should be fixed in https://github.com/rootstrap/ios-base/blob/b71af8701ce3a0b324e6b5fbae973ef0410adcc0/ios-base/Networking/APIClient.swift#L168. This doesn't affect model's errors which will continue using the hash

The api base is changing that in https://github.com/rootstrap/rails_api_base/pull/107

**Comment by glm4** [comment]
Solved in #71. Closing...
