### ISSUE TITLE
Add Swift 4.0+ support

### ISSUE THREAD

**Issue by glm4** [rootstrap/ios-base#80]
Create a new branch for Swift 4.0+ support.

**Comment by pMalvasio** [comment]
Besides the basic changes, this should include also the implementation of the protocols Decodable/Encodable instead of using SwiftyJSON for parsing the models. @glm4 WDYT?

**Comment by glm4** [comment]
Agree, that would be nice too.

**Comment by glm4** [comment]
Solved in PR #83
