### ISSUE TITLE
add .patch case to JSONEncoding.default in APIClient

### ISSUE THREAD

**Issue by cuylerquint** [rootstrap/ios-base#98]
Great repo 😄!! Attempted to push a branch and PR but got 'denied access' 🤕.  would love to contribute!  Took me a while to figure out why my server wasn't processing the request correctly but found out that patch wasn't using JSON encoding at default 😉 

one liner in my attempted PR:
```
class func defaultEncoding(forMethod method: HTTPMethod) -> ParameterEncoding {
    switch method {
    case .post, .put:
      return JSONEncoding.default
    default:
      return URLEncoding.default
    }
  }
```
 to 
```
class func defaultEncoding(forMethod method: HTTPMethod) -> ParameterEncoding {
    switch method {
    case .post, .put, .patch:
      return JSONEncoding.default
    default:
      return URLEncoding.default
    }
  }
```

**Comment by glm4** [comment]
Hey @cuylerquint, thanks for contributing. Good catch, we will be updating it soon. 💪

**Comment by cuylerquint** [comment]
thanks @glm4  no problem,  love helping out 👍

**Comment by glm4** [comment]
Solved!
